### ISSUE TITLE
Boards are a bit loose on the shell

### ISSUE THREAD

**Issue by vrtlspd** [CasualCodersProjects/DS4-Type-C#11]
Why not include the screw hole in the boards? I think it has enough space for it. Instead of including your logo on the top, you should put it below the LED. Please consider this, I'm not the only one complaining about this.

**Comment by CC-Ian** [comment]
I appreciate the concern and the idea, though I truly do not believe my design has the room to make this work. I believe there is a clearance issue between the hole, and the physically deeper USB Type C receptacle.

As it stands, I have no intention of implementing this change, as once the last few boards sell out on Tindie, I no longer intend to sell these.

At any rate, the project is fully open source, so you're free to fork the project and attempt to add the mounting hole yourself. You could even replace the USB C receptacle with a shallower version, provided you can find a suitable replacement online.
