### ISSUE TITLE
I have a JDS-030 controller, how can I help?

### ISSUE THREAD

**Issue by adamboy7** [CasualCodersProjects/DS4-Type-C#2]
I have a multimeter, a digital caliper, but I've never used PCB building software before. Do I just need to provide dimensions and continuity between pins? I'm also not sure what to make of the two chips in the upper right bottom side, I think one of them _might_ be a mosfet? I'm not sure, how can I help?
![20220308_201626](https://user-images.githubusercontent.com/4840111/157355776-5759fb3b-207d-4caf-8856-fc46cbdb36f8.jpg)
![20220308_201807](https://user-images.githubusercontent.com/4840111/157355786-4d22c454-28ef-4ee2-b4f7-e3b11d4d315a.jpg)

**Comment by 12ian3** [comment]
You're in luck, because I just added 030 to this repo. All the required files to fab boards should be associated with this commit: https://github.com/12ian3/DS4-Type-C/commit/adab8a4524bf502062ee0863a6762c9f91443fbd

**Comment by adamboy7** [comment]
> You're in luck, because I just added 030 to this repo. All the required files to fab boards should be associated with this commit: [adab8a4](https://github.com/12ian3/DS4-Type-C/commit/adab8a4524bf502062ee0863a6762c9f91443fbd)

Yaay! Thank you!
