### ISSUE TITLE
030 does not work

### ISSUE THREAD

**Issue by 12ian3** [CasualCodersProjects/DS4-Type-C#5]
Board 030 has the incorrect pinout. Vcc should be pins 5 and 6 of the FPC, and pin 8 of the FPC is the Annode of the RGB LED

**Comment by 12ian3** [comment]
Should've been fixed last night with the latest push. Will leave this issue open until confirmed.

**Comment by GrimKriegor** [comment]
As of 5adb2fcc35c69b2be41fc0fdc34ab9da58bddd39, 030 seems to be working perfectly.
C to C charging has not been tested.
Thank you for your efforts!
![030](https://user-images.githubusercontent.com/1028205/178798404-2f394d17-d68f-402f-aa08-221ae5a8f63b.jpg)
