### ISSUE TITLE
Gerber still uses old LEDs

### ISSUE THREAD

**Issue by crashniels** [CasualCodersProjects/DS4-Type-C#9]
Got myself a few of the 011 and 030 boards. The LEDs listed are the newer ones but the Gerber hasn't been updated for these it seems. They still use the old 7 pin ones (mine are 4 that I ordered).

**Comment by 12ian3** [comment]
Confirmed this is an issue. Please export the Gerbers from source for the time being. Fixing this is an incredibly low priority for me at the moment. I'll mark it down, and repair it when I get around to it.

**Comment by CC-Ian** [comment]
This is for all intents and purposes fixed as of 11/22/22, however I intend to make a few additional changes to 001 when I get some more time and will close this once those changes have been added.

prepackaged Gerbers are current for:
- 011
- 030
- 040/05X
